Improve movieme

diff --git a/bin/movieme b/bin/movieme
--- a/bin/movieme
+++ b/bin/movieme
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # MOVIE ME as in: "MOVIE ME AN ANIMATED GIF FROM THIS MOVIE, DAMMIT"
 #
@@ -18,13 +18,39 @@
 #   ~/Desktop/holman-backflip-on-fire.mov 3.9 1.75
 
 # cleanup
+if [ -z "$1" ]
+then
+  echo "Usage movieme <filename>. Max 10000 seconds movie"
+  exit 1
+fi
+if [ -z "$2" ]
+then
+  start_time=0
+else
+  start_time=$2
+fi
+if [ -z "$3" ]
+then
+  total_time=10000
+else
+  total_time=$3
+fi
+if ! which ffmpeg; then
+  echo "ffmpeg not found!!\nInstall using brew install imagemagick"
+  exit 1
+fi
+if ! which gifme; then
+  echo "gifme not found!!\nInstall using gem install gifme"
+  exit 1
+fi
 rm -rf /tmp/movieme
 
 # create tmp dir
 mkdir -p /tmp/movieme
 
 # split the movie into constituent frames
-ffmpeg -i $1 -f image2 -vf "scale=iw*sar:ih" -ss $2 -t $3 -r 7 /tmp/movieme/d-%05d.png
+ffmpeg -i $1 -f image2 -vf "scale=iw*sar:ih" -ss $start_time -t $total_time -r 7 /tmp/movieme/d-%05d.png
 
+echo "Completed splitting. Animating Gifs now."
 # ANIMATE
-gifme /tmp/movieme/* -d 0
+gifme /tmp/movieme/* -d 0 --width=2000
